controller_maneger:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: "diff_drive_controller/DiffDriveController"
      # left_wheel: "left_wheel_joint"
      # right_wheel: "right_wheel_joint"
      # publish_rate: 30
      # enable_odom_tf: true
      # odom_frame_id: "odom"
      # base_frame_id: "base_footprint"
      # wheel_separation: 0.5
      # wheel_radius: 0.1
      # cmd_vel_timeout: 0.5

    joint_broad:
      type: "joint_state_broadcaster/JointStateBroadcaster"
      # publish_rate: 30
      # joint_names: ["left_wheel_joint", "right_wheel_joint"]

diff_cont:
  ros__parameters:

    publish_rate: 50
    base_frame_id: "base_link"

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false